language: python
dist: xenial
python:
  - "2.7"
virtualenv:
  system_site_packages: false
cache: pip
install:
  - pip install flake8
  - pip install -r requirements.txt
  - sudo apt-get update
  - sudo apt-get install sox ffmpeg
script:
  - flake8 audio_degrader
  - flake8 tests
  - python -m pytest tests/test_*.py -vv
